### ISSUE TITLE
有可能发生死锁

### ISSUE THREAD

**Issue by 60813** [xiajunsongfan/zkclient#1]
你好，关于分布式锁，simpleLock这个类，只在init中注册了watch，watch是一次性的，当两个线程调用lock时，第一个线程消费watch的事件后，没有重新注册watch到zk，可能导致第二个线索无listener wake。

另外两个线程时，如果线程1和线程2同时create节点时，watcher可能只会收到一次消息，这个将必定导致一个线程死掉

如下代码可重现问题：
@Test
    public void lock2()  {
        final Lock lock = zk.getLock("/test");
        new Thread(new Runnable() {
			@Override
			public void run() {
				// TODO Auto-generated method stub
				lock.lock(0);
				System.out.println("1 locked");
				try {
					Thread.sleep(10000);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}).start();
        
        new Thread(new Runnable() {
			@Override
			public void run() {
				// TODO Auto-generated method stub
				lock.lock(0);
				System.out.println("2 locked");
				try {
					Thread.sleep(10000);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}).start();
    }

**Comment by xiajunsongfan** [comment]
这并不是一个死锁问题，lock.lock(0);之后需要调用lock.unlock();，你可以再尝试一下

**Comment by xiajunsongfan** [comment]
init方法中使用了 client.listenChild(this.lockPath, lockListener); 来封装了watcher事件，后续的事件都会进行回调，不是一次性的watcher。

**Comment by 60813** [comment]
嗯嗯，不好意思是我看错了。你的listener每次事件完之后封装了重新注册一个watch上去，呵呵，现在看明白了。谢谢~
