### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by 60813** [xiajunsongfan/zkclient#2]
你好，com.xj.zk.lock.LockListener.check(String seq, List<String> locks) 这个方法的如下代码：

           if (seq_ > lock_) {
                isLock = false;
                continue;
            }
当前线程创建的临时节点不是最小时，也就是seq_>lock_时，就肯定是false了，下方的 continue是否应该改为break呢，否则后面的循环显得没有必要了。

**Comment by 60813** [comment]
你好，还有一个疑问，com.xj.zk.lock.LockListener.listen(String path, EventType eventType, byte[] data)这个方法的如下代码：

           if (check(lock, locks)) {
                acqLock = lock;
                entry.getValue().release();
            }

是不是改为

           if (check(lock, locks)) {
                acqLock = lock;
                entry.getValue().release();
                break;
            }
更为合适呢，因为当前不管有多少个线程在等待，只要一个线程获取了锁，其他线程应该是继续等待的，所以这个实际上获得线程后可以直接break了而不需要后面继续循环判断。

**Comment by xiajunsongfan** [comment]
非常感谢，这两个已经修改
