### ISSUE TITLE
再提一个疑似缺陷

### ISSUE THREAD

**Issue by 60813** [xiajunsongfan/zkclient#3]
你好，com.xj.zk.lock.SimpleLock.lock(long timeout) 这个方法，当传入一个时间，比如10毫秒时

以下代码将会执行：

String newPath = this.client.create(this.seqPath, "".getBytes(), CreateMode.EPHEMERAL_SEQUENTIAL);

将会在zk创建一个临时节点，比如   /lock/0000000002，假如此时锁被其他机器的线程占用并且超过10毫秒，则以下代码将不阻塞，并且会返回false

            if (timeout >= 1) {
                islock = lockObj.tryAcquire(timeout, TimeUnit.MILLISECONDS);
            } 

倘若他返回false，则使用方没有理由再调用unlock。比如concurrent包中Lock接口的tryLock方法就有如下定义：

Lock lock = ...;
 if (lock.tryLock()) {
   try {
     // manipulate protected state
   } finally {
     lock.unlock();
   }
 } else {
   // perform alternative actions
 }}

我们在使用concurrent的tryLock时，如果tryLock返回false还调用unlock的话，是会抛出异常的，所以在finally中是使用如下代码解锁：

finally{
  if (locked){
     lock.unlock();
  }
}

这样假如我也按这种方式写解锁代码，则会导致0000000002一直存在（在client不close的情况下一直存在），而此时的其他线程或机器去调用lock方法，则会一直阻塞并等待0000000002。

**Comment by xiajunsongfan** [comment]
jdk中lock.tryLock()思想是获取一个许可，lock.unlock();释放一个许可，tryLock返回false时是不能调用unlock返回一个许可的，其实jdk也可以不抛异常同时也不释放一个许可，它抛异常的目的是想让开发者明白没有获取到锁。zk这个unlock()方法本意是想统一调用方式，我在返回false时处理掉这个节点吧，这样你调用就不会有问题了。

**Comment by 60813** [comment]
嗯，好的。
