### ISSUE TITLE
有个严谨问题

### ISSUE THREAD

**Issue by 60813** [xiajunsongfan/zkclient#4]
您好，simpleLock的lock方法，86行

      String newPath = this.client.create(this.seqPath, "".getBytes(), CreateMode.EPHEMERAL_SEQUENTIAL);
        currentLock.set(newPath);
        String[] paths = newPath.split("/");
        final String seq = paths[paths.length - 1];
        lockListener.addQueue(seq, lockObj);

这里的本意是创建一个临时节点，引起listener来release这个semaphore
理论上，由于内存比网络调用快，create后，lockListener.addQueue(seq, lockObj); 这句会先于listener的方法执行，但在实际情况中，这里可能不够严谨，假如listener的回调方法穿插在这两句的中间执行，将导致该线程的lockObj.acquire();被阻塞，直到其他进程或线程中有lock行为创建新的子临时节点为止。

因此这里是否考虑将create和addQueue这一段加个内部ReentrantLock,然后再将listener的方法中操作waitThread的地方也加上这个锁，保持这两段的同步。使lock时的顺序严格按照如下3步：

1.创建临时节点
2.添加semophore到监听器
3.监听器释放semophore

**Comment by xiajunsongfan** [comment]
确实有这个隐患，我也发现了一个更严重的问题，当网络不稳定导致部分机器下线，临时节点被删除，网络恢复后再有事件触发时，会出现多台机器同时获得锁，没有事件触发就会导致一直等待。

**Comment by 60813** [comment]
嗯，是的，而且貌似curator也有这个问题。

**Comment by 60813** [comment]
可以在发现丢失连接的时间时让lock抛出异常，被使用者捕捉后触发unlock，并在unlock中捕捉网络异常，直接解锁。

**Comment by xiajunsongfan** [comment]
处理了一下，但还是不太理想。

**Comment by 60813** [comment]
我down下来也研究一下
